mysql:
  container_name: {CONTAINER_NAME_MYSQL}
  ports:
    - "{PORT_MYSQL}:3306"
  env_file:
    - ./conf/env_file/production/env
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
prestashop16:
  container_name: {CONTAINER_NAME_WEB}
  dockerfile: ./conf/docker/Dockerfile16
  build: .
  ports:
    - "{PORT_WEB}:80"
  links:
    - smtp
    - mysql
  env_file:
    - ./conf/env_file/production/env
    - ./conf/env_file/production/env16
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
prestashop17:
  container_name: {CONTAINER_NAME_WEB1}
  dockerfile: ./conf/docker/Dockerfile17
  build: .
  ports:
    - "{PORT_WEB1}:80"
  links:
    - smtp
    - mysql
  env_file:
    - ./conf/env_file/production/env
    - ./conf/env_file/production/env17
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
smtp:
  container_name: {CONTAINER_NAME_SMTP}
  ports:
    - "{PORT_SMTP}:1080"
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"

